### ISSUE TITLE
Svrha aplikacije

### ISSUE THREAD

**Issue by sbuljat** [LuKi1406/Flask-API#1]
Kolegice možete li objasniti koja je svrha odnosno primjena ove aplikacije? Registracija i upravljanje korisnicima je nešto što svaki sustav mora imati, to smo imali i u primjerima s predavanja, ovdje mi nedostaje API koji bi se bavio s nekim konkretnim problemom. Primjera radi Vaše kolege su radile API za pizzerije (kreiranje pizze, narudžbe, etc.), bug ticketing, itd.

Možda sam nešto propustio pa Vas molim za ispravak ako je tomu tako.

**Comment by LuKi1406** [comment]
Poštovanje,

Nisam radila API za zavrsni projekt nego cisto primjer API-a, kao sto je
todos API.

Lp,
Josipa Gligić

uto, 19. svi 2020. 13:25 Stjepan Buljat <notifications@github.com> je
napisao:

**Comment by sbuljat** [comment]
Kolegice kolokvij 1 se odnosi izradu REST API aplikacije koja uključuje Users API, a istovremeno i neki API kojim se projekt bavi - kao što sam ranije naveo. U ovom slučaju ne možemo Vam ponuditi više od 10 bodova. Jel Vam to u redu?

**Comment by LuKi1406** [comment]
Poštovanje,

Odgovara mi 10 bodova.

Lp,
Josipa Gligić

sri, 20. svi 2020. 16:15 Stjepan Buljat <notifications@github.com> je
napisao:

**Comment by sbuljat** [comment]
U redu.
